apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-availability.dev.alm.dev.20231019135633.0.0
spec:
  refName: where-for-dinner-availability.dev.alm.dev
  version: 20231019135633.0.0
  releaseNotes: |
    Release v20231019135633.0.0 of package where-for-dinner-availability.dev.alm.dev
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/ucp-with-syncer/wfd/where-for-dinner-availability-dev-bundle@sha256:4f2b565ba31890aeb4b0615b5b644372dc7996599d3d66d9c675f9c7bf16978f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          default: ""
        replicas:
          title: Replicas
          type: integer
          default: 1
        port:
          title: Port
          type: integer
          default: 8080
        hostname:
          title: Hostname
          type: string
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          default: tap-ingress-selfsigned
        http_route:
          type: object
          additionalProperties: false
          nullable: true
          properties:
            gateways:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  protocol:
                    type: string
                    default: ""
                  name:
                    type: string
                    default: ""
              default:
              - protocol: https
                name: default-gateway

