apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.tanzu.vmware.com.20240225161744.0.0
spec:
  refName: tanzu-java-web-app.tanzu.vmware.com
  version: 20240225161744.0.0
  releaseNotes: |
    Release v20240225161744.0.0 of package tanzu-java-web-app.tanzu.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/supplychain/workload/tanzu-java-web-app-bundle@sha256:6a758db93f4550356d9c33221e2d74eec313d17280c2aef6007c411e61b75a61
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          description: Used to generate resource names for HttpRoute and Ingress objects.
          default: tanzu-java-web-app
        replicas:
          type: integer
          nullable: true
          description: Overrides the default Deployment.spec.replicas set by the Supply Chain.
          default: null
        strategy:
          nullable: true
          description: Overrides the default Deployment.spec.strategy set by the Supply Chain.
          default: null
        livenessProbe:
          nullable: true
          description: Overrides the default Deployment.spec.containers[0].livenessProbe set by the Supply Chain.
          default: null
        readinessProbe:
          nullable: true
          description: Overrides the default Deployment.spec.containers[0].readinessProbe set by the Supply Chain.
          default: null
        resources:
          nullable: true
          description: Overrides the default Deployment.spec.containers[0].resources set by the Supply Chain.
          default: null
        env:
          nullable: true
          description: Overrides the default Deployment.spec.containers[0].env set by the Supply Chain.
          default: null
        securityContext:
          nullable: true
          description: Overrides the default Deployment.spec.containers[0].securityContext set by the Supply Chain.
          default: null
        port:
          type: integer
          description: Sets the Port for the backend referenced by the Ingress or HttpRoute object.
          default: 8080
        hostname:
          type: string
          description: Sets the Host for the Ingress object (class=contour). If unset, no Ingress will be created.
          default: ""
        cluster_issuer:
          type: string
          description: Sets the CertManager ClusterIssuer for the Ingress object.
          default: tap-ingress-selfsigned
        http_route:
          type: object
          additionalProperties: false
          nullable: true
          description: Sets the ParentRefs for the HttpRoute object. If set to null, no HttpRoute will be created.
          properties:
            gateways:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  protocol:
                    type: string
                    default: ""
                  name:
                    type: string
                    default: ""
              default:
              - protocol: https
                name: default-gateway
        service:
          title: Service
          type: object
          additionalProperties: false
          nullable: true
          properties:
            ports:
              title: Overrides the default Service.spec.ports set by the Supply Chain.
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  name:
                    type: string
                    default: http
                  port:
                    type: integer
                    default: 8080
                  targetPort:
                    type: integer
                    default: 8080
              default: []
