apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: appsso-starter-java.dev.alm.dev.20260128173400.0.0
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
spec:
  refName: appsso-starter-java.dev.alm.dev
  version: 20260128173400.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: supply-chain-docker-dev-local.usw1.packages.broadcom.com/tap-install/tbs/appsso-starter-java-dev-bundle@sha256:3026fbecf8add7a5bc3cc27492ab4e8bf295a1bdfb7efe09ff4c9068cfccfac7
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

