apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: appsso-starter-java.dev.alm.dev.20260114192536.0.0
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
spec:
  refName: appsso-starter-java.dev.alm.dev
  version: 20260114192536.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: supply-chain-docker-dev-local.usw1.packages.broadcom.com/tap-install/tbs/appsso-starter-java-dev-bundle@sha256:ab33254a8f6794a2d3933cb75e9f3f276e53b2ac76f32b9343f183cd4a24144d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

