apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: appsso-starter-java.dev.alm.dev.20260619164042.0.0+build.bda9ba9
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
spec:
  refName: appsso-starter-java.dev.alm.dev
  version: 20260619164042.0.0+build.bda9ba9
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: supply-chain-docker-dev-local.usw1.packages.broadcom.com/tap-install/tbs/appsso-starter-java-dev-bundle@sha256:b52318d57edf9e7ceb871b52004dc6a4730aecf8245d814f349f7199572e3979
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

