apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ucp.ucp-package.lever-v2.dev.alm.dev.20231021000546.0.0
spec:
  refName: ucp.ucp-package.lever-v2.dev.alm.dev
  version: 20231021000546.0.0
  releaseNotes: |
    Release v20231021000546.0.0 of package ucp.ucp-package.lever-v2.dev.alm.dev
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/ucp-with-syncer/wfd/ucp.ucp-package.lever-v2-dev-bundle@sha256:f4068838ffa62a2000dffae9867097c0e6fcb08d9c4a8a5f9ef2d0aa5b8fb97b
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          title: Workload name
          type: string
          default: ""
        replicas:
          title: Replicas
          type: integer
          default: 1
        port:
          title: Port
          type: integer
          default: 8080
        hostname:
          title: Hostname
          type: string
          default: ""
        cluster_issuer:
          title: Cluster Issuer
          type: string
          default: tap-ingress-selfsigned
        http_route:
          type: object
          additionalProperties: false
          nullable: true
          properties:
            gateways:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  protocol:
                    type: string
                    default: ""
                  name:
                    type: string
                    default: ""
              default:
              - protocol: https
                name: default-gateway

