apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
    name: appbuild
spec:
    defines:
        group: supplychains.tanzu.vmware.com
        kind: AppBuild
        plural: appbuilds
        version: v1alpha1
    description: Build a Server type workload from source and store the Carvel package in Git
    stages:
        - componentRef:
            name: source-git-provider-1.0.0
          name: source-git-provider
          securityContext:
            runAs: workload
        - componentRef:
            name: buildpack-build-1.0.0
          name: buildpack-build
        - componentRef:
            name: conventions-1.0.0
          name: conventions
        - componentRef:
            name: app-config-server-1.0.0
          name: app-config-server
        - componentRef:
            name: carvel-package-1.0.0
          name: carvel-package
        - componentRef:
            name: git-writer-pr-1.0.0
          name: git-writer-pr
    config:
        overrides:
          - path: spec.build
            value:
                serviceAccountName: "default"
                builder:
                  kind: "clusterbuilder"
                  name: "default"
                cache:
                  image: ""
                  enabled: false
          - path: spec.registry
            value:
                repository: "adhol-playground/supplychain/workload"
                server: "us-east4-docker.pkg.dev"
          - path: spec.gitOps
            value:
                baseBranch: "main"
                subPath: "dev/packages"
                url: "https://github.com/atmandhol/tap-gitops"
          - path: spec.carvel.serviceAccountName
            value: default
          - path: spec.carvel.packageDomain
            value: "default.tap"
          - path: spec.carvel.valuesSecretName
            value: ""
          - path: spec.carvel.iaasAuthEnabled
            value: true
          - path: spec.carvel.caCertData
            value: ""
        defaults:
          - path: spec.source.git.branch
            value: main
          - path: spec.source.git.url
            value: https://github.com/vmware-tanzu/application-accelerator-samples