apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: node-express.dev.alm.dev.20250721211337.0.0
  labels:
    app.kubernetes.io/part-of: node-express
spec:
  refName: node-express.dev.alm.dev
  version: 20250721211337.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: supply-chain-docker-dev-local.usw1.packages.broadcom.com/tap-install/tbs/node-express-dev-bundle@sha256:fcf12d2a72671b94cda5f1b3ab15facced8f1d3fea2242482c6c02a2885e52a3
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

