apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: node-express.dev.alm.dev.20251119162815.0.0
  labels:
    app.kubernetes.io/part-of: node-express
spec:
  refName: node-express.dev.alm.dev
  version: 20251119162815.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: supply-chain-docker-dev-local.usw1.packages.broadcom.com/tap-install/tbs/node-express-dev-bundle@sha256:77fb28d27ebb019ccbc827253317957a18e43786029d0beb8fe968bceabcdfd7
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""
          minLength: 1

