apiVersion: supplychains.tanzu.vmware.com/v1alpha1
kind: AppBuild
metadata:
  name: spring-petclinic
spec:
  source:
    git:
      branch: "main"
      url: "https://github.com/atmandhol/sample-apps.git"
    subPath: "source/spring-petclinic"
  carvel:
    packageName: "spring-petclinic"
  env:
  - name: "SPRING_ENV_PROFILE"
    value: "dev"
