apiVersion: supplychains.tanzu.vmware.com/v1alpha1
kind: WebApp
metadata:
  name: spring-petclinic-deploy
spec:
  registry:
    repository: "adhol-playground/supplychain/workload"
    server: "us-east4-docker.pkg.dev"
  source:
    git:
      branch: "main"
      url: "https://github.com/atmandhol/sample-apps.git"
    subPath: "source/spring-petclinic"
