apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: ucp.ucp-package.lever-v2-rmq
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{"local-source-proxy.apps.tanzu.vmware.com":"gcr.io/adhol-playground/lsp:dev-where-for-dinner-availability@sha256:e0df791afe23906ed5b99243cc575e5aafff1bc575374c1cb4c2d6b6ca67ccdb"},"creationTimestamp":"2023-10-18T21:35:11Z","generation":2,"labels":{"app.kubernetes.io/part-of":"where-for-dinner-availability","apps.tanzu.vmware.com/workload-type":"web"},"name":"ucp.ucp-package.lever-v2","namespace":"dev","resourceVersion":"27206860","uid":"f1a4d3fc-1416-4f07-8d37-d6732125edd6"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"},{"name":"BP_MAVEN_ACTIVE_PROFILES","value":"streams"}]},"env":[{"name":"spring_profiles_active","value":"rabbitmq"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"ports","value":[{"containerPort":8080,"name":"http","port":80}]},{"name":"api_descriptor","value":{"description":"Core Where For Dinner service for retrieving dining availability","location":{"path":"/v3/api-docs"},"owner":"where-for-dinner-team","system":"where-for-dinner","type":"openapi"}}],"resources":{"limits":{"cpu":"1500m","memory":"750M"},"requests":{"cpu":"100m","memory":"500M"}},"serviceClaims":[{"name":"rmq","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"msgbroker-where-for-dinner"}}],"source":{"image":"gcr.io/adhol-playground/lsp:dev-where-for-dinner-availability@sha256:e0df791afe23906ed5b99243cc575e5aafff1bc575374c1cb4c2d6b6ca67ccdb"}}}
    local-source-proxy.apps.tanzu.vmware.com: gcr.io/adhol-playground/lsp:dev-where-for-dinner-availability@sha256:e0df791afe23906ed5b99243cc575e5aafff1bc575374c1cb4c2d6b6ca67ccdb
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: where-for-dinner-availability
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: ucp.ucp-package.lever-v2
spec:
  name: rmq
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: msgbroker-where-for-dinner
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: ucp.ucp-package.lever-v2

