---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
 name: tanzu-java-web-app-sync
spec:
  serviceAccountName: default
  fetch:
  - git:
      url: https://github.com/atmandhol/tap-gitops
      ref: origin/tap
      subPath: packages/tanzu-java-web-app.dev.alm.dev
  template:
  - ytt: {}
  deploy:
  - kapp:
      rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-package-and-pkgi-install-role
rules:
  - apiGroups: ["data.packaging.carvel.dev"]
    resources: ["packages"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["packaging.carvel.dev"]
    resources: ["packageinstalls"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: app-cr-role
# rules:
# - apiGroups: ["apps"]
#   resources: ["deployments"]
#   verbs: ["get", "list", "create", "update", "delete"]
# - apiGroups: [""]
#   resources: ["configmaps", "services"]
#   verbs: ["get", "list", "create", "update", "delete"]
# - apiGroups: ["networking.k8s.io"]
#   resources: ["ingresses"]
#   verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carvel-gitops
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: app-package-and-pkgi-install-role
  apiGroup: rbac.authorization.k8s.io