apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: petc.test.tap.20230330210540.0.0
spec:
  refName: petc.test.tap
  version: 20230330210540.0.0
  releaseNotes: |
    Release v20230330210540.0.0 of package petc.test.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: gcr.io/adhol-playground/tbs/petc-test-bundle@sha256:fd5071f15ae188a806315dc62c84df2ca050c31e5eedef8f5da6ce435bc5cb5d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

