apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucp-test-worker.ucp-package.lever-v2
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/workload-type: worker
    app.kubernetes.io/component: run
    carto.run/workload-name: ucp-test-worker.ucp-package.lever-v2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: tanzu-java-web-app
      apps.tanzu.vmware.com/auto-configure-actuators: "false"
      apps.tanzu.vmware.com/workload-type: worker
      carto.run/workload-name: ucp-test-worker.ucp-package.lever-v2
      conventions.carto.run/framework: spring-boot
      tanzu.app.live.view: "true"
      tanzu.app.live.view.application.actuator.path: actuator
      tanzu.app.live.view.application.actuator.port: "8080"
      tanzu.app.live.view.application.flavours: spring-boot
      tanzu.app.live.view.application.name: ucp-test-worker.ucp-package.lever-v2
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/sample-accelerators/tanzu-java-web-app?sub_path=/
        boot.spring.io/version: 2.7.3
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          spring-boot-convention/spring-boot-actuator-probes
          spring-boot-convention/app-live-view-appflavour-check
          spring-boot-convention/app-live-view-connector-boot
          spring-boot-convention/app-live-view-appflavours-boot
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"tanzu-java-web-app","apps.tanzu.vmware.com/workload-type":"worker"},"name":"ucp-test-worker.ucp-package.lever-v2","namespace":"dev"},"spec":{"source":{"git":{"ref":{"commit":"6db88c7a7e7dec1843809b058195b68480c4c12a"},"url":"https://github.com/sample-accelerators/tanzu-java-web-app"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-java-web-app
        apps.tanzu.vmware.com/auto-configure-actuators: "false"
        apps.tanzu.vmware.com/workload-type: worker
        carto.run/workload-name: ucp-test-worker.ucp-package.lever-v2
        conventions.carto.run/framework: spring-boot
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.path: actuator
        tanzu.app.live.view.application.actuator.port: "8080"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: ucp-test-worker.ucp-package.lever-v2
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.health.probes.enabled="true" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: us-east4-docker.pkg.dev/adhol-playground/ucp-with-syncer/wfd/ucp-test-worker.ucp-package.lever-v2-dev@sha256:be396742a583d8c8061530510c786c0fdd47622a96a37901d12b26873a11b15c
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000
        startupProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
      serviceAccountName: default

