apiVersion: tekton.dev/v1
kind: Task
metadata:
    name: deployer
spec:
    description: Deploys K8s resources to the cluster.
    params:
        - default: ""
          description: Path to the yaml to deploy
          name: subpath
          type: string
        - description: Name of the kapp app to be deployed
          name: kapp-app-name
          type: string
    results:
        - name: message
          type: string
    stepTemplate:
        computeResources: {}
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
                type: RuntimeDefault
    steps:
        - computeResources: {}
          image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:546db16bb63fcd79133b266b9dcf12722629a8a3475906ca37b5ce0e3f153326
          name: deploy-using-kubectl
          script: |-
            #!/bin/bash

            set -uo pipefail

            MESSAGE=$(kapp deploy --app $(params.kapp-app-name) -f "$(workspaces.content.path)/$(params.subpath)" --yes)
            if [ $? -ne 0 ]; then
              printf "kapp deploy failed. $MESSAGE" | tee $(results.message.path)
              exit 1
            fi
    workspaces:
        - description: The folder where the yaml is
          name: content
