apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: spring-petclinic.tanzu.dev.20240126144800.0.0
spec:
  refName: spring-petclinic.tanzu.dev
  version: 20240126144800.0.0
  releaseNotes: |
    Release v20240126144800.0.0 of package spring-petclinic.tanzu.dev
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: us-east4-docker.pkg.dev/adhol-playground/supplychain/workload/spring-petclinic-bundle@sha256:14259d58e696bb9c90acb6a4128d1d1a8d0175897d17de4d007b2e198fe5c37a
      template:
      - ytt:
          paths:
          - '-'
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
